import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { ArrowLeft, Save, Rocket, Plus, X, Settings2, Cpu, Server, Zap, Shield, KeyRound, Bot, MessageSquare, Eye, EyeOff, Link2, CheckCircle2, Wand, Loader2, ExternalLink, Play, Send, AlertCircle, Bug, FolderKanban, Store, ArrowRight, Mic, MicOff, HelpCircle, FileEdit, Terminal, ChevronDown, ChevronUp, Copy, Brain, Wrench, Info, AlertTriangle, Trash2, RefreshCw, Code2, FileCode } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent } from "@/components/ui/tabs";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Slider } from "@/components/ui/slider";
import { Switch } from "@/components/ui/switch";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter, DialogTrigger } from "@/components/ui/dialog";
import { toast } from "@/hooks/use-toast";
import { categories, getActiveSkills, getActiveMCPs, mockAgents, mockCredentials } from "@/data/mockData";
import { isMcpConfigured, subscribeMcpStore } from "@/data/mcpCredentialStore";
import { CapabilityPickerDialog } from "@/components/CapabilityPickerDialog";
import { AIStatusPill } from "@/components/AIStatusPill";
import { RunDualView, RunningIndicator, type TranscriptEvent } from "@/components/RunViews";

// 基于 Anthropic 对 Claude 的 prompting 最佳实践，提供一份"脚手架"模板，
// 帮助用户按结构补全自己的提示词，而不是套用某个具体行业的成品。
const promptScaffold = `# 角色与目标
你是 <在这里写明角色，例如：资深的 XX 专家>，主要服务对象是 <用户画像>。
你的核心目标是 <用一句话写清交付什么结果，例如：在 5 分钟内输出可执行的 XX 报告>。

# 背景与上下文
- 业务场景：<这个 Agent 会被在什么场景下调用>
- 关键术语：<列出 3~5 个领域内必须正确使用的术语及其含义>
- 已知约束：<时间、数据范围、合规要求等>

# 你拥有的能力
- MCP / Skill 列表会在运行时由系统注入，请优先使用工具而非凭记忆作答。
- 调用工具前，先用一句话说明"为什么调用、期望得到什么"。
- 工具失败或返回为空时，主动说明并尝试备选方案，不要伪造数据。

# 思考方式（重要）
在回答复杂问题前，请先在 <thinking> 标签内完成以下步骤，再给出最终答复：
1. 拆解用户意图，识别隐含前提
2. 列出可选方案并比较权衡
3. 选择方案并规划工具调用顺序

# 输出规范
- 使用 Markdown 组织结构，关键信息加粗
- 引用工具返回的数据时，注明来源（MCP / Skill 名称）
- 数字、日期、专有名词与原始数据保持一致
- 默认使用与用户相同的语言

# 边界与拒答
- 涉及 <敏感操作 / 写库 / 外发> 时，必须先与用户二次确认
- 不在回复中暴露密钥、Token、内部链接
- 超出能力范围时，明确告知并推荐替代方案

# 示例（可选但强烈推荐）
<example>
用户：<典型问题>
助手：<期望的回答样式，包含工具调用与最终输出>
</example>`;


const skills = getActiveSkills();
const mcps = getActiveMCPs();
const subagents = mockAgents
  .filter((a) => a.kind === "agent" && (a.publishScope === "marketplace" || a.status === "project"))
  .map((a) => ({
    name: a.name,
    description: a.description,
    skills: a.skills,
    mcpServers: a.mcpServers,
    scope: (a.publishScope === "marketplace" ? "market" : "project") as "market" | "project",
  }));

const CreateAgentManualPage = () => {
  const navigate = useNavigate();

  // Basic (filled at publish time)
  const [name, setName] = useState("");
  const [description, setDescription] = useState("");
  const [category, setCategory] = useState(categories[0]);
  const [publishOpen, setPublishOpen] = useState(false);
  const [specOpen, setSpecOpen] = useState(false);
  const [specFormat, setSpecFormat] = useState<"yaml" | "json">("yaml");
  const [generatingMeta, setGeneratingMeta] = useState(false);
  const [avatarSeed, setAvatarSeed] = useState(() => Math.random().toString(36).slice(2, 10));
  const [generatingAvatar, setGeneratingAvatar] = useState(false);
  const avatarUrl = `https://api.dicebear.com/7.x/bottts-neutral/svg?seed=${encodeURIComponent(avatarSeed)}&backgroundColor=dbeafe,fde68a,bbf7d0,fecaca,e9d5ff`;
  const regenerateAvatar = () => {
    setGeneratingAvatar(true);
    setTimeout(() => {
      setAvatarSeed(Math.random().toString(36).slice(2, 10) + Date.now().toString(36));
      setGeneratingAvatar(false);
    }, 600);
  };

  // Model
  const [model, setModel] = useState("claude-sonnet-4-6");

  // Prompt
  const [systemPrompt, setSystemPrompt] = useState("");
  const [generatingPrompt, setGeneratingPrompt] = useState(false);
  const [promptAutoGenerated, setPromptAutoGenerated] = useState(false);

  // Bindings
  const [selSkills, setSelSkills] = useState<string[]>([]);
  const [selMCPs, setSelMCPs] = useState<string[]>([]);
  const [selSubagents, setSelSubagents] = useState<string[]>([]);
  const [subagentGapOpen, setSubagentGapOpen] = useState(false);

  // Subscribe to MCP vault store so missing-credential badges live update
  const [, setVaultTick] = useState(0);
  useEffect(() => {
    const unsub = subscribeMcpStore(() => setVaultTick((t) => t + 1));
    return () => { unsub(); };
  }, []);

  const isMcpAvailableInVault = (name: string) => {
    const meta = mcps.find((m) => m.name === name);
    if (!meta) return false;
    if (!meta.requiresCredential) return true;
    return isMcpConfigured(name);
  };

  // Env
  const [persistentFs, setPersistentFs] = useState(true);
  const [mcpCredentialMap, setMcpCredentialMap] = useState<Record<string, string>>({});

  // FengSheng NEXT bot
  const [fsAppKey, setFsAppKey] = useState("");
  const [fsAppSecret, setFsAppSecret] = useState("");
  const [fsRobotCode, setFsRobotCode] = useState("");
  const [fsSecretVisible, setFsSecretVisible] = useState(false);
  const [fsConnected, setFsConnected] = useState(false);

  // Agent Hub publishing (optional) — 仅控制是否发布到 Hub 进行可视化监控
  const [hubEnabled, setHubEnabled] = useState(false);

  // Controlled tab (so we can jump users between steps)
  const [currentTab, setCurrentTab] = useState("capability");

  // Debug — three streams: assistant chat (left), agent run (right), runtime logs (right bottom)
  type PromptSuggestion = { id: string; addition: string; summaryNote: string; status: "pending" | "adopted" | "rejected" };
  type ChatMsg = { role: "user" | "assistant"; content: string; suggestion?: PromptSuggestion };
  type RunMsg = { role: "user" | "assistant"; content: string; tool?: string; status?: "ok" | "error" };
  const [assistantInput, setAssistantInput] = useState("");
  const [assistantMessages, setAssistantMessages] = useState<ChatMsg[]>([]);
  const [assistantThinking, setAssistantThinking] = useState(false);
  const [debugInput, setDebugInput] = useState("");
  const [runMessages, setRunMessages] = useState<RunMsg[]>([]);
  const [debugRunning, setDebugRunning] = useState(false);
  const [voiceRecording, setVoiceRecording] = useState(false);

  // Mandatory debug gating
  const [debugPassed, setDebugPassed] = useState(false);
  const [debugAttempted, setDebugAttempted] = useState(false);
  const [debugLastError, setDebugLastError] = useState(false);


  // Track all changes auto-applied during debugging — surfaced at save time
  type DebugChange = { ts: string; summary: string; field: "prompt" | "binding" | "model" | "credential" };
  const [debugChanges, setDebugChanges] = useState<DebugChange[]>([]);
  const recordChange = (field: DebugChange["field"], summary: string) => {
    setDebugChanges((c) => [...c, { ts: new Date().toLocaleTimeString("zh-CN", { hour12: false }), field, summary }]);
  };

  // Runtime logs (Cloud Code style) — persistent panel, user can collapse
  type LogLevel = "info" | "tool" | "thought" | "warn" | "error" | "result";
  type LogEntry = { id: number; ts: string; level: LogLevel; message: string; meta?: string };
  const [debugLogs, setDebugLogs] = useState<LogEntry[]>([]);
  const logIdRef = (globalThis as any).__logIdRef ?? { current: 0 };
  (globalThis as any).__logIdRef = logIdRef;

  const pushLog = (level: LogLevel, message: string, meta?: string) => {
    const ts = new Date().toLocaleTimeString("zh-CN", { hour12: false }) + "." + String(Date.now() % 1000).padStart(3, "0");
    setDebugLogs((l) => [...l, { id: ++logIdRef.current, ts, level, message, meta }]);
  };

  // Publish flow (single-step save)


  // After each run, AI proposes optimization (user must adopt to apply)
  const autoOptimizeAfterRun = (userInput: string) => {
    setTimeout(() => {
      const undocumented = [
        ...selMCPs.filter((m) => !systemPrompt.includes(m)),
        ...selSkills.filter((s) => !systemPrompt.includes(s)),
      ];
      if (undocumented.length > 0) {
        const target = undocumented[0];
        setAssistantMessages((m) => [
          ...m,
          {
            role: "assistant",
            content: `我注意到你绑定了「${target}」，但系统提示词里没有说明它的用途。\n\n请用一句话告诉我：在什么场景下应该调用「${target}」？我会据此完善提示词。`,
          },
        ]);
        return;
      }
      if (systemPrompt.includes("# 来自调试的补充指引")) return;
      const addition = `\n\n# 来自调试的补充指引\n- 用户曾以「${userInput}」类问题进行测试，遇到该类问题时应优先：\n  1. 拆解任务目标，明确需要哪些 MCP / Skill\n  2. 引用工具返回的数据并标注来源\n  3. 输出结构化结果，避免冗余寒暄`;
      const suggestion: PromptSuggestion = {
        id: `s-${Date.now()}`,
        addition,
        summaryNote: `补充提示词：基于「${userInput}」类任务，新增"任务拆解 / 来源标注 / 结构化输出"工作流`,
        status: "pending",
      };
      setAssistantMessages((m) => [
        ...m,
        {
          role: "assistant",
          content: `根据本轮调试，我建议在系统提示词中补充「任务拆解 → 工具选择 → 来源标注 → 结构化输出」的工作流，以更好地匹配「${userInput}」类任务。`,
          suggestion,
        },
      ]);
    }, 900);
  };

  const updateSuggestionStatus = (id: string, status: "adopted" | "rejected") => {
    setAssistantMessages((msgs) =>
      msgs.map((m) => (m.suggestion?.id === id ? { ...m, suggestion: { ...m.suggestion, status } } : m))
    );
  };

  const adoptSuggestion = (s: PromptSuggestion) => {
    if (s.status !== "pending") return;
    setSystemPrompt((p) => p.trim() + s.addition);
    recordChange("prompt", s.summaryNote);
    updateSuggestionStatus(s.id, "adopted");
    toast({ title: "已采纳建议", description: "系统提示词已更新" });
  };

  const rejectSuggestion = (s: PromptSuggestion) => {
    if (s.status !== "pending") return;
    updateSuggestionStatus(s.id, "rejected");
  };

  const runDebug = (overrideInput?: string) => {
    const text = (overrideInput ?? debugInput).trim();
    if (!text) return;
    setRunMessages((m) => [...m, { role: "user", content: text }]);
    setDebugInput("");
    setDebugRunning(true);
    setDebugAttempted(true);
    setDebugLastError(false);

    const tool = selMCPs[0] || selSkills[0] || "内置推理";
    pushLog("info", `[session] 接收用户输入`, `text="${text}"`);
    pushLog("info", `[runtime] 启动容器 sandbox-${Math.random().toString(36).slice(2, 6)}`, `image=cloud-code:1.4.2 · workspace=/workspace`);
    pushLog("info", `[model] ${model} · stream=true · context=${4096 + text.length}`);

    setTimeout(() => pushLog("thought", `[reasoning] 解析用户意图：识别到任务类型，准备调用 ${tool}`), 120);
    setTimeout(() => pushLog("tool", `[tool_use] 调用 ${tool}`, `args={"query":"${text.slice(0, 40)}"} · timeout=30s`), 280);
    setTimeout(() => pushLog("info", `[mcp] ↔ ${tool} HTTP 200 · 142ms`), 460);
    setTimeout(() => pushLog("tool", `[tool_result] ${tool} 返回 1 条结果`, `bytes=312`), 520);
    setTimeout(() => pushLog("thought", `[reasoning] 整合工具返回，生成结构化回复`), 600);

    setTimeout(() => {
      setRunMessages((m) => [
        ...m,
        {
          role: "assistant",
          status: "ok",
          tool,
          content: `已通过 ${tool} 完成响应：根据你的输入「${text}」生成结果（模拟输出）。`,
        },
      ]);
      pushLog("result", `[done] 推理完成 · 用时 698ms · tokens in=312 out=128`);
      setDebugRunning(false);
      setDebugPassed(true);
      autoOptimizeAfterRun(text);
    }, 700);
  };

  const sendAssistantMessage = () => {
    const text = assistantInput.trim();
    if (!text) return;
    setAssistantMessages((m) => [...m, { role: "user", content: text }]);
    setAssistantInput("");
    setAssistantThinking(true);
    setTimeout(() => {
      // Heuristic: detect intents like "改提示词" / "绑定 X" / general clarification reply
      let reply = "";
      if (/提示词|prompt/i.test(text)) {
        const note = `\n\n# 用户调试反馈\n- ${text}`;
        setSystemPrompt((p) => p + note);
        recordChange("prompt", `根据你的反馈追加到提示词："${text.slice(0, 30)}${text.length > 30 ? "…" : ""}"`);
        reply = `好的，我已经把这条要求追加到系统提示词里了。可以在右侧继续发起一轮调试验证效果。`;
      } else if (/绑定|添加.*MCP|加上.*Skill/i.test(text)) {
        reply = `好的。请在「能力配置」里勾选具体的 MCP / Skill；如果你告诉我服务名称，我也可以直接帮你添加。`;
      } else {
        // Treat as clarification answer for purpose of an MCP/Skill
        const undocumented = [
          ...selMCPs.filter((m) => !systemPrompt.includes(m)),
          ...selSkills.filter((s) => !systemPrompt.includes(s)),
        ];
        if (undocumented[0]) {
          const target = undocumented[0];
          const addition = `\n\n# 能力说明\n- 「${target}」：${text}`;
          setSystemPrompt((p) => p + addition);
          recordChange("prompt", `补充「${target}」的用途说明：${text.slice(0, 40)}${text.length > 40 ? "…" : ""}`);
          reply = `已记录「${target}」的用途，并写入系统提示词。如果还有其他工具需要说明，告诉我即可。`;
        } else {
          reply = `收到。你可以让我"修改提示词"、"补充某个能力的用途"，或在右侧直接发起一轮调试。`;
        }
      }
      setAssistantMessages((m) => [...m, { role: "assistant", content: reply }]);
      setAssistantThinking(false);
    }, 1600);
  };

  const toggleVoice = () => {
    if (voiceRecording) {
      setVoiceRecording(false);
      // Mock transcription
      const mockText = "帮我查询昨天的快递订单状态";
      setDebugInput((prev) => (prev ? `${prev} ${mockText}` : mockText));
      toast({ title: "语音已转写", description: mockText });
    } else {
      setVoiceRecording(true);
      toast({ title: "开始语音输入", description: "再次点击结束录音" });
    }
  };

  const handleAutoGenerateMeta = () => {
    setGeneratingMeta(true);
    setTimeout(() => {
      const skillNames = selSkills.slice(0, 2).join("、");
      const mcpNames = selMCPs.slice(0, 2).join("、");
      const capSummary = [skillNames, mcpNames].filter(Boolean).join(" + ") || "通用对话";
      const guessedName = selMCPs[0]
        ? `${selMCPs[0]} 助手`
        : selSkills[0]
        ? `${selSkills[0]} 智能体`
        : "通用 AI 助手";
      const guessedDesc = `基于 ${capSummary} 的智能体，可根据用户输入自动调用对应能力完成任务。`;
      const guessedCategory =
        selMCPs.some((m) => /邮件|mail/i.test(m)) ? "办公协作" :
        selMCPs.some((m) => /数据|db|sql/i.test(m)) ? "数据分析" :
        selSkills.some((s) => /代码|code/i.test(s)) ? "研发提效" :
        categories[0];
      if (!name) setName(guessedName);
      if (!description) setDescription(guessedDesc);
      setCategory(guessedCategory);
      setGeneratingMeta(false);
      toast({ title: "已根据当前配置生成基础信息" });
    }, 600);
  };

  const toggle = (list: string[], setList: (v: string[]) => void, name: string) =>
    setList(list.includes(name) ? list.filter((x) => x !== name) : [...list, name]);



  const handleAutoGeneratePrompt = () => {
    setGeneratingPrompt(true);
    setTimeout(() => {
      const roleLine = name.trim() ? `你是「${name.trim()}」` : "你是一个专业的 AI 智能体";
      const descLine = description.trim() ? `，${description.trim()}。` : "，致力于高质量地完成用户交付的任务。";

      const skillLines = selSkills.length
        ? selSkills.map((s) => {
            const meta = skills.find((x) => x.name === s);
            return `- ${s}${meta ? `：${meta.description}` : ""}`;
          }).join("\n")
        : "- （未绑定 Skill）";

      const mcpLines = selMCPs.length
        ? selMCPs.map((s) => {
            const meta = mcps.find((x) => x.name === s);
            return `- ${s}${meta ? `：${meta.description}` : ""}`;
          }).join("\n")
        : "- （未绑定 MCP 服务）";

      const subLines = selSubagents.length
        ? selSubagents.map((s) => `- ${s}`).join("\n")
        : "";

      const generated = `# 角色
${roleLine}${descLine}

# 你拥有的能力
## MCP 服务（外部工具）
${mcpLines}

## Skills（原子能力）
${skillLines}
${subLines ? `\n## 可调度的子智能体\n${subLines}\n` : ""}
# 工作流程
1. 仔细理解用户意图，必要时主动澄清关键信息。
2. 根据任务类型，从上述能力中选择最合适的工具组合。
3. 调用工具前简要说明计划；调用后基于结果迭代下一步。
4. 对涉及外部数据写入或敏感操作的步骤，先与用户确认再执行。

# 输出规范
- 使用清晰的 Markdown 结构组织回答。
- 引用工具返回的数据时，注明来源（MCP / Skill 名称）。
- 遇到不确定或工具不可用时，如实告知，不要编造结果。

# 约束
- 严格遵守公司数据安全与合规要求。
- 不要在回复中暴露密钥、Token 或其他凭证。`;

      setSystemPrompt(generated);
      setGeneratingPrompt(false);
      toast({ title: "已根据当前能力生成系统提示词", description: `MCP ${selMCPs.length} · Skill ${selSkills.length} · 子智能体 ${selSubagents.length}` });
    }, 800);
    setPromptAutoGenerated(true);
  };

  // 进入「系统提示词」步骤时，若尚未生成过，自动用 AI 生成一版供用户修改
  useEffect(() => {
    if (currentTab === "prompt" && !promptAutoGenerated && !generatingPrompt && !systemPrompt.trim()) {
      handleAutoGeneratePrompt();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [currentTab]);

  // ── Step validation ──────────────────────────────────────────────
  const capabilityComplete = selMCPs.length > 0 || selSkills.length > 0;
  const promptComplete = systemPrompt.trim().length >= 20;
  // 对外接入是可选的，但若启用了丰声 NEXT 必须完成连接（Agent Hub 仅是开关）
  const channelsValid = !fsConnected || (!!fsAppKey && !!fsAppSecret && !!fsRobotCode);
  const debugComplete = debugPassed && !debugLastError;

  const stepStatus = {
    capability: capabilityComplete ? "done" : "todo",
    prompt: capabilityComplete ? (promptComplete ? "done" : "todo") : "locked",
    channels: capabilityComplete && promptComplete ? (channelsValid ? "done" : "warn") : "locked",
    debug: capabilityComplete && promptComplete ? (debugComplete ? "done" : debugAttempted ? (debugLastError ? "warn" : "todo") : "todo") : "locked",
  } as const;

  const blockingReasons: { msg: string; jumpTo: string }[] = [];
  if (!capabilityComplete) blockingReasons.push({ msg: "请至少绑定 1 个 MCP 或 Skill", jumpTo: "capability" });
  if (!promptComplete) blockingReasons.push({ msg: "请完善系统提示词（不少于 20 字）", jumpTo: "prompt" });
  if (!channelsValid) blockingReasons.push({ msg: "已启用的对外接入尚未完成连接，请补齐或关闭", jumpTo: "channels" });
  if (!debugComplete) blockingReasons.push({ msg: debugLastError ? "上一次调试出现错误，请修复后重新调试" : "保存前必须在「调试」中完成至少一次成功运行", jumpTo: "debug" });
  const canSave = blockingReasons.length === 0;

  const openPublish = () => {
    if (!canSave) {
      const first = blockingReasons[0];
      toast({ title: "无法保存", description: first.msg, variant: "destructive" });
      setCurrentTab(first.jumpTo);
      return;
    }
    handleAutoGenerateMeta();
    setPublishOpen(true);
  };

  const handleSave = () => {
    if (!name.trim()) {
      toast({ title: "请填写智能体名称", variant: "destructive" });
      return;
    }
    toast({ title: "已保存到项目管理", description: `${name} · ${category}（如需发布，请前往项目管理或详情页发布）` });
    setPublishOpen(false);
    navigate("/project-agents");
  };

  // PickerDialog moved to shared component: CapabilityPickerDialog

  // Build spec for YAML / JSON viewer
  const specObject = {
    name: name || "未命名智能体",
    description: description || "",
    category,
    model: { id: model, speed: "standard" },
    system_prompt: systemPrompt,
    skills: selSkills,
    mcp_servers: selMCPs.map((m) => ({
      name: m,
      credential: mcpCredentialMap[m] || null,
    })),
    subagents: selSubagents,
    fengsheng_next: {
      enabled: fsConnected,
      app_key: fsAppKey || null,
      robot_code: fsRobotCode || null,
      persistent: persistentFs,
    },
  };
  const specJson = JSON.stringify(specObject, null, 2);
  const toYaml = (obj: unknown, indent = 0): string => {
    const pad = "  ".repeat(indent);
    if (obj === null || obj === undefined) return "null";
    if (typeof obj === "string") {
      if (obj.includes("\n")) return `|-\n${obj.split("\n").map((l) => pad + "  " + l).join("\n")}`;
      return /[:#&*!|>'"%@`]/.test(obj) ? JSON.stringify(obj) : obj;
    }
    if (typeof obj === "number" || typeof obj === "boolean") return String(obj);
    if (Array.isArray(obj)) {
      if (obj.length === 0) return "[]";
      return "\n" + obj.map((item) => {
        if (typeof item === "object" && item !== null) {
          const inner = toYaml(item, indent + 1).trimStart();
          return `${pad}- ${inner}`;
        }
        return `${pad}- ${toYaml(item, indent + 1)}`;
      }).join("\n");
    }
    if (typeof obj === "object") {
      const entries = Object.entries(obj as Record<string, unknown>);
      if (entries.length === 0) return "{}";
      return entries.map(([k, v]) => {
        const val = toYaml(v, indent + 1);
        if (val.startsWith("\n")) return `${pad}${k}:${val}`;
        return `${pad}${k}: ${val}`;
      }).join("\n");
    }
    return String(obj);
  };
  const specYaml = toYaml(specObject).replace(/^\n/, "");
  const specContent = specFormat === "yaml" ? specYaml : specJson;

  const copySpec = async () => {
    await navigator.clipboard.writeText(specContent);
    toast({ title: "已复制到剪贴板" });
  };
  const downloadSpec = () => {
    const blob = new Blob([specContent], { type: specFormat === "yaml" ? "text/yaml" : "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${(name || "agent").replace(/\s+/g, "-")}.${specFormat}`;
    a.click();
    URL.revokeObjectURL(url);
  };


  return (
    <div className="flex-1 overflow-auto animate-fade-in">
      {/* Header */}
      <div className="border-b border-border bg-card/40 px-6 py-3 flex items-center justify-between sticky top-0 z-10">
        <div className="flex items-center gap-3">
          <button
            onClick={() => navigate(-1)}
            className="text-muted-foreground hover:text-foreground flex items-center gap-1 text-xs"
          >
            <ArrowLeft className="w-3.5 h-3.5" />
            返回
          </button>
          <div>
            <h1 className="text-base font-semibold leading-tight">手动组装智能体</h1>
            <p className="text-[11px] text-muted-foreground">面向开发者的精确配置模式</p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <Button size="sm" variant="outline" className="h-8 text-xs gap-1.5" onClick={() => setSpecOpen(true)}>
            <FileCode className="w-3.5 h-3.5" />
            查看配置文档
          </Button>
          <Button
            size="sm"
            className="h-8 text-xs gap-1.5"
            onClick={openPublish}
            disabled={!canSave}
            title={canSave ? "保存为新版本" : blockingReasons[0]?.msg}
          >
            <Save className="w-3.5 h-3.5" />
            保存
          </Button>
        </div>
      </div>

      <div className="max-w-6xl mx-auto px-6 py-5">
        {/* 步骤指引 */}
        {(() => {
          const steps: { key: string; label: string; sub: string }[] = [
            { key: "capability", label: "1. 能力配置", sub: "选择模型 / MCP / Skill" },
            { key: "prompt", label: "2. 系统提示词", sub: "定义角色与工作方式" },
            { key: "channels", label: "3. 对外接入", sub: "丰声 NEXT / Agent Hub（可选）" },
            { key: "debug", label: "4. 调试并保存", sub: "至少一次成功运行后才能保存" },
          ];
          return (
            <div className="mb-4 rounded-lg border border-border bg-card p-3">
              <div className="flex items-center w-full">
                {steps.map((s, i) => {
                  const status = (stepStatus as Record<string, string>)[s.key] ?? "todo";
                  const active = currentTab === s.key;
                  const dotCls =
                    status === "done" ? "bg-emerald-500 text-white border-emerald-500" :
                    status === "warn" ? "bg-amber-500 text-white border-amber-500" :
                    status === "locked" ? "bg-muted text-muted-foreground border-border" :
                    active ? "bg-primary text-primary-foreground border-primary" :
                    "bg-background text-foreground border-border";
                  const labelCls =
                    status === "locked" ? "text-muted-foreground" :
                    active ? "text-foreground font-medium" : "text-foreground";
                  const connectorCls =
                    status === "done" ? "bg-emerald-500/60" : "bg-border";
                  return (
                    <div key={s.key} className="flex items-center flex-1 last:flex-none min-w-0">
                      <button
                        type="button"
                        onClick={() => setCurrentTab(s.key)}
                        disabled={status === "locked"}
                        className="flex items-center gap-2 group min-w-0 shrink-0"
                      >
                        <span className={`w-6 h-6 rounded-full border flex items-center justify-center text-[11px] shrink-0 ${dotCls} ${active ? "ring-2 ring-primary ring-offset-2 ring-offset-background" : ""}`}>
                          {status === "done" ? <CheckCircle2 className="w-3.5 h-3.5" /> :
                           status === "warn" ? <AlertTriangle className="w-3.5 h-3.5" /> :
                           i + 1}
                        </span>
                        <div className="text-left min-w-0">
                          <div className={`text-[11px] leading-tight truncate ${active ? "text-primary font-semibold" : labelCls}`}>{s.label}</div>
                          <div className="text-[10px] text-muted-foreground leading-tight truncate">{s.sub}</div>
                        </div>
                      </button>
                      {i < steps.length - 1 && (
                        <div className="flex-1 mx-3 flex items-center gap-2 min-w-[24px]">
                          <div className={`h-px flex-1 ${connectorCls}`} />
                          <ArrowRight className="w-3 h-3 text-muted-foreground shrink-0" />
                          <div className={`h-px flex-1 ${connectorCls}`} />
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>
          );
        })()}

        <Tabs value={currentTab} onValueChange={setCurrentTab}>

          {/* Capability: 基座模型 + MCP + Skill + Subagent */}
          <TabsContent value="capability" className="mt-4 space-y-4">
            {/* 模型配置 */}
            <div className="border border-border rounded-lg p-5 space-y-5 bg-card">
              <div>
                <Label className="text-xs">模型配置</Label>
                <Select value={model} onValueChange={setModel}>
                  <SelectTrigger className="mt-1.5 h-8 text-xs"><SelectValue /></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="claude-sonnet-4-6" className="text-xs">Claude Sonnet 4.6（推荐）</SelectItem>
                    <SelectItem value="claude-haiku-3-5" className="text-xs">Claude Haiku 3.5（快速）</SelectItem>
                    <SelectItem value="gpt-4o" className="text-xs">GPT-4o</SelectItem>
                    <SelectItem value="gemini-2.5-pro" className="text-xs">Gemini 2.5 Pro</SelectItem>
                    <SelectItem value="deepseek-v3" className="text-xs">DeepSeek V3</SelectItem>
                    <SelectItem value="qwen-max" className="text-xs">Qwen Max</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>

            {/* MCP 绑定 */}
            <div className="border border-border rounded-lg p-5 bg-card">
              <div className="flex items-center justify-between mb-3">
                <div>
                  <Label className="text-xs flex items-center gap-1.5"><Server className="w-3.5 h-3.5 text-muted-foreground" />MCP 绑定</Label>
                  <p className="text-[10px] text-muted-foreground mt-0.5">连接外部系统；部分 MCP 需要绑定凭据后才能调用</p>
                </div>
                <CapabilityPickerDialog items={mcps} selected={selMCPs} onToggle={(n) => toggle(selMCPs, setSelMCPs, n)} icon={<Server className="w-3.5 h-3.5" />} label="MCP" marketLink="/" deployBadge={(n) => mcps.find((m) => m.name === n)?.deployment ?? "云端"} trigger={<Button size="sm" variant="outline" className="h-7 text-xs gap-1 shrink-0"><Plus className="w-3 h-3" />添加 MCP</Button>} />
              </div>
              {selMCPs.length === 0 ? null : (
                <div className="flex flex-wrap gap-2">
                  {selMCPs.map((mcpName) => {
                    const mcpMeta = mcps.find((m) => m.name === mcpName);
                    const needsCred = !!mcpMeta?.requiresCredential;
                    const creds = mockCredentials.filter((c) => c.mcpServer === mcpName);
                    const current = mcpCredentialMap[mcpName] ?? (creds.length === 1 ? creds[0].id : "");
                    const credMissing = needsCred && !current;
                    return (
                      <div key={mcpName} className={`inline-flex items-center gap-1.5 rounded-md border pl-2 pr-1 py-1 text-xs ${credMissing ? "border-amber-300 bg-amber-50/40 dark:bg-amber-950/20" : "border-border bg-card"}`}>
                        <Server className="w-3 h-3 text-primary shrink-0" />
                        <span className="font-medium max-w-[140px] truncate">{mcpName}</span>
                        {needsCred && (
                          <Popover>
                            <PopoverTrigger asChild>
                              <button className={`inline-flex items-center gap-0.5 text-[10px] px-1 py-0.5 rounded ${credMissing ? "text-amber-700 hover:bg-amber-100" : "text-emerald-700 hover:bg-emerald-100"}`} title="凭据">
                                {credMissing ? <AlertTriangle className="w-2.5 h-2.5" /> : <KeyRound className="w-2.5 h-2.5" />}
                                {credMissing ? "未绑定" : "已绑定"}
                              </button>
                            </PopoverTrigger>
                            <PopoverContent className="w-64 p-3" align="start">
                              <Label className="text-[11px] text-muted-foreground">选择凭据</Label>
                              {creds.length === 0 ? (
                                <div className="mt-2 space-y-2">
                                  <p className="text-[11px] text-amber-600">该 MCP 暂无可用凭据</p>
                                  <Button size="sm" variant="outline" className="h-7 text-xs gap-1 w-full" onClick={() => navigate("/vault")}>
                                    前往凭据管理 <ExternalLink className="w-3 h-3" />
                                  </Button>
                                </div>
                              ) : (
                                <Select value={current} onValueChange={(v) => setMcpCredentialMap({ ...mcpCredentialMap, [mcpName]: v })}>
                                  <SelectTrigger className="h-7 text-xs mt-1.5"><SelectValue placeholder="选择凭据" /></SelectTrigger>
                                  <SelectContent>
                                    {creds.map((c) => (
                                      <SelectItem key={c.id} value={c.id} className="text-xs">{c.name}</SelectItem>
                                    ))}
                                  </SelectContent>
                                </Select>
                              )}
                            </PopoverContent>
                          </Popover>
                        )}
                        {!needsCred && (
                          <Badge variant="outline" className="border-emerald-300 text-emerald-700 bg-emerald-50/60 dark:bg-emerald-950/30 text-[10px] h-4 px-1">免凭据</Badge>
                        )}
                        <button onClick={() => toggle(selMCPs, setSelMCPs, mcpName)} className="text-muted-foreground hover:text-destructive p-0.5" title="移除">
                          <X className="w-3 h-3" />
                        </button>
                      </div>
                    );
                  })}
                </div>
              )}
            </div>

            {/* Skill 绑定 */}
            <div className="border border-border rounded-lg p-5 bg-card">
              <div className="flex items-center justify-between mb-3">
                <div>
                  <Label className="text-xs flex items-center gap-1.5"><Zap className="w-3.5 h-3.5 text-muted-foreground" />Skill 绑定</Label>
                  <p className="text-[10px] text-muted-foreground mt-0.5">预制能力包，让智能体掌握特定领域的工作流</p>
                </div>
                <CapabilityPickerDialog items={skills} selected={selSkills} onToggle={(n) => toggle(selSkills, setSelSkills, n)} icon={<Zap className="w-3.5 h-3.5" />} label="Skill" marketLink="/" trigger={<Button size="sm" variant="outline" className="h-7 text-xs gap-1 shrink-0"><Plus className="w-3 h-3" />添加 Skill</Button>} />
              </div>
              {selSkills.length === 0 ? null : (
                <div className="flex flex-wrap gap-2">
                  {selSkills.map((s) => {
                    const meta = skills.find((x) => x.name === s);
                    return (
                      <div key={s} className="inline-flex items-center gap-1.5 rounded-md border border-border bg-card pl-2 pr-1 py-1 text-xs" title={meta?.description}>
                        <Zap className="w-3 h-3 text-primary shrink-0" />
                        <span className="font-medium max-w-[160px] truncate">{s}</span>
                        {meta?.scope === "project" && (
                          <Badge variant="outline" className="text-[10px] h-4 px-1 border-border">项目</Badge>
                        )}
                        <button onClick={() => toggle(selSkills, setSelSkills, s)} className="text-muted-foreground hover:text-destructive p-0.5" title="移除">
                          <X className="w-3 h-3" />
                        </button>
                      </div>
                    );
                  })}
                </div>
              )}
            </div>

            {/* 子智能体绑定 */}
            <div className="border border-border rounded-lg p-5 bg-card">
              <div className="flex items-center justify-between mb-3">
                <div>
                  <Label className="text-xs flex items-center gap-1.5"><Bot className="w-3.5 h-3.5 text-muted-foreground" />子智能体绑定</Label>
                  <p className="text-[10px] text-muted-foreground mt-0.5">从智能体广场挑选已发布的智能体作为子智能体，主智能体可调度它们协同完成任务（可选）</p>
                </div>
                <CapabilityPickerDialog
                  items={subagents.map((a) => ({ name: a.name, description: a.description, scope: a.scope }))}
                  selected={selSubagents}
                  onToggle={(n) => toggle(selSubagents, setSelSubagents, n)}
                  icon={<Bot className="w-3.5 h-3.5" />}
                  label="子智能体"
                  marketLink="/"
                  trigger={<Button size="sm" variant="outline" className="h-7 text-xs gap-1 shrink-0"><Plus className="w-3 h-3" />添加子智能体</Button>}
                />
              </div>
              {(() => {
                const allMissing = new Set<string>();
                selSubagents.forEach((name) => {
                  const sub = subagents.find((a) => a.name === name);
                  sub?.mcpServers.forEach((m) => { if (!isMcpAvailableInVault(m)) allMissing.add(m); });
                });
                if (allMissing.size === 0) return null;
                return (
                  <div className="border border-amber-300 bg-amber-50/60 dark:bg-amber-950/20 rounded-md px-3 py-2 mb-2 flex items-center justify-between gap-3">
                    <div className="flex items-center gap-2 min-w-0">
                      <AlertTriangle className="w-3.5 h-3.5 text-amber-600 shrink-0" />
                      <span className="text-[11px] text-amber-800 dark:text-amber-300 truncate">
                        有 {allMissing.size} 个子智能体依赖的 MCP 尚未在 MCP 管理中配置凭据
                      </span>
                    </div>
                    <Button size="sm" variant="outline" className="h-7 text-[11px] border-amber-300 text-amber-700 hover:bg-amber-100 shrink-0" onClick={() => setSubagentGapOpen(true)}>
                      查看并配置
                    </Button>
                  </div>
                );
              })()}
              {selSubagents.length === 0 ? null : (
                <div className="space-y-2">
                  {selSubagents.map((name) => {
                    const sub = subagents.find((a) => a.name === name);
                    if (!sub) return (
                      <div key={name} className="border border-border rounded-md p-3 flex items-center justify-between">
                        <span className="text-xs flex items-center gap-1.5"><Bot className="w-3 h-3 text-primary" />{name}</span>
                        <button onClick={() => toggle(selSubagents, setSelSubagents, name)} className="text-muted-foreground hover:text-destructive p-1"><X className="w-3.5 h-3.5" /></button>
                      </div>
                    );
                    const missingMcps = sub.mcpServers.filter((m) => !isMcpAvailableInVault(m));
                    return (
                      <div key={name} className="border border-border rounded-md p-3 space-y-2">
                        <div className="flex items-start justify-between gap-2">
                          <div className="min-w-0 flex-1">
                            <div className="flex items-center gap-1.5">
                              <Bot className="w-3.5 h-3.5 text-primary shrink-0" />
                              <span className="text-xs font-medium truncate">{sub.name}</span>
                              <Badge variant="outline" className="text-[10px] h-4 px-1.5 border-border">来自广场</Badge>
                            </div>
                            <p className="text-[11px] text-muted-foreground mt-1 line-clamp-2 leading-relaxed">{sub.description}</p>
                          </div>
                          <button onClick={() => toggle(selSubagents, setSelSubagents, name)} className="text-muted-foreground hover:text-destructive p-1 shrink-0" title="移除"><X className="w-3.5 h-3.5" /></button>
                        </div>
                        {(sub.skills.length > 0 || sub.mcpServers.length > 0) && (
                          <div className="border-t border-border pt-2 space-y-1.5">
                            {sub.mcpServers.length > 0 && (
                              <div className="flex items-start gap-2 flex-wrap">
                                <span className="text-[10px] text-muted-foreground shrink-0 mt-0.5">继承 MCP</span>
                                {sub.mcpServers.map((m) => {
                                  const ok = isMcpAvailableInVault(m);
                                  return (
                                    <Badge key={m} variant="outline" className={`text-[10px] h-4 px-1.5 gap-1 ${ok ? "border-emerald-300 text-emerald-700 bg-emerald-50/60" : "border-amber-300 text-amber-700 bg-amber-50/60"}`}>
                                      <Server className="w-2.5 h-2.5" />{m}
                                      {!ok && <AlertTriangle className="w-2.5 h-2.5" />}
                                    </Badge>
                                  );
                                })}
                              </div>
                            )}
                            {sub.skills.length > 0 && (
                              <div className="flex items-start gap-2 flex-wrap">
                                <span className="text-[10px] text-muted-foreground shrink-0 mt-0.5">继承 Skill</span>
                                {sub.skills.map((s) => (
                                  <Badge key={s} variant="outline" className="text-[10px] h-4 px-1.5 gap-1 border-border">
                                    <Zap className="w-2.5 h-2.5" />{s}
                                  </Badge>
                                ))}
                              </div>
                            )}
                            {missingMcps.length > 0 && (
                              <p className="text-[10px] text-amber-700 dark:text-amber-400 flex items-center gap-1">
                                <AlertTriangle className="w-2.5 h-2.5" />
                                {missingMcps.length} 个 MCP 尚未配置凭据，需在 MCP 管理中补齐
                              </p>
                            )}
                          </div>
                        )}
                      </div>
                    );
                  })}
                </div>
              )}
            </div>

            {/* 子智能体缺口配置 - 独立弹窗 */}
            <Dialog open={subagentGapOpen} onOpenChange={setSubagentGapOpen}>
              <DialogContent className="max-w-lg">
                <DialogHeader>
                  <DialogTitle className="text-sm">补齐子智能体所需 MCP 凭据</DialogTitle>
                </DialogHeader>
                <div className="space-y-2 max-h-[60vh] overflow-auto">
                  {(() => {
                    const map = new Map<string, string[]>();
                    selSubagents.forEach((name) => {
                      const sub = subagents.find((a) => a.name === name);
                      sub?.mcpServers.forEach((m) => {
                        if (!isMcpAvailableInVault(m)) map.set(m, [...(map.get(m) ?? []), name]);
                      });
                    });
                    if (map.size === 0) return <p className="text-xs text-muted-foreground py-4 text-center">所有依赖 MCP 已就绪</p>;
                    return Array.from(map.entries()).map(([mcp, owners]) => (
                      <div key={mcp} className="border border-border rounded-md p-3 flex items-center justify-between gap-3">
                        <div className="min-w-0">
                          <div className="flex items-center gap-1.5">
                            <Server className="w-3 h-3 text-primary shrink-0" />
                            <span className="text-xs font-medium truncate">{mcp}</span>
                            <Badge className="bg-amber-100 text-amber-700 hover:bg-amber-100 border-0 text-[10px] h-4">未配置</Badge>
                          </div>
                          <p className="text-[10px] text-muted-foreground mt-0.5 truncate">被以下子智能体使用：{owners.join("、")}</p>
                        </div>
                        <Button size="sm" variant="outline" className="h-7 text-[11px] shrink-0" onClick={() => { setSubagentGapOpen(false); navigate("/vault"); }}>
                          前往配置
                        </Button>
                      </div>
                    ));
                  })()}
                </div>
                <DialogFooter>
                  <Button variant="outline" size="sm" className="h-8 text-xs" onClick={() => setSubagentGapOpen(false)}>关闭</Button>
                </DialogFooter>
              </DialogContent>
            </Dialog>

            <div className="flex justify-end">
              <Button
                size="sm"
                className="h-8 text-xs gap-1.5"
                disabled={!capabilityComplete}
                onClick={() => setCurrentTab("prompt")}
                title={capabilityComplete ? "下一步：系统提示词" : "请至少绑定 1 个 MCP 或 Skill"}
              >
                下一步：系统提示词 <ArrowRight className="w-3 h-3" />
              </Button>
            </div>

          </TabsContent>

          {/* Prompt */}
          <TabsContent value="prompt" className="mt-4">
            <div className="border border-border rounded-lg p-5 bg-card">
              <div className="flex items-start justify-between gap-3 mb-2">
                <div>
                  <Label className="text-xs">系统提示词</Label>
                  <p className="text-[10px] text-muted-foreground">定义智能体身份、行为约束和输出格式</p>
                </div>
                <Button
                  size="sm"
                  variant="outline"
                  className="h-7 text-xs gap-1.5 border-primary/40 text-primary hover:bg-primary/10 hover:text-primary"
                  onClick={handleAutoGeneratePrompt}
                  disabled={generatingPrompt}
                >
                  {generatingPrompt ? <Loader2 className="w-3 h-3 animate-spin" /> : <Wand className="w-3 h-3" />}
                  AI 自动生成
                </Button>
              </div>
              <Textarea className="font-mono text-xs leading-relaxed" rows={18} value={systemPrompt} onChange={(e) => setSystemPrompt(e.target.value)} />
              <div className="flex items-center justify-between mt-2">
                <p className="text-[10px] text-muted-foreground">
                  {systemPrompt.length} 字符 · 将根据已绑定的 {selSkills.length} 个 Skill 与 {selMCPs.length} 个 MCP 生成
                </p>
                <Button
                  size="sm"
                  variant="ghost"
                  className="h-7 text-xs gap-1"
                  onClick={() => {
                    if (systemPrompt.trim() && !window.confirm("将用提示词脚手架覆盖当前内容，是否继续？")) return;
                    setSystemPrompt(promptScaffold);
                    toast({
                      title: "已导入提示词脚手架",
                      description: "按段落把 < > 占位符替换为你 Agent 的实际信息",
                    });
                  }}
                >
                  <FileEdit className="w-3 h-3" />
                  使用提示词脚手架
                </Button>
              </div>
            </div>
            <div className="flex justify-between mt-3">
              <Button size="sm" variant="ghost" className="h-8 text-xs gap-1" onClick={() => setCurrentTab("capability")}>
                <ArrowLeft className="w-3 h-3" /> 上一步
              </Button>
              <Button
                size="sm"
                className="h-8 text-xs gap-1.5"
                disabled={!promptComplete}
                onClick={() => setCurrentTab("channels")}
                title={promptComplete ? "下一步：对外接入" : "请完善系统提示词（不少于 20 字）"}
              >
                下一步：对外接入 <ArrowRight className="w-3 h-3" />
              </Button>
            </div>
          </TabsContent>

          {/* 对外接入：子智能体 + 丰声 NEXT + Agent Hub */}
          <TabsContent value="channels" className="mt-4 space-y-4">
            <div className="border border-dashed border-border rounded-lg px-4 py-3 bg-muted/30 flex items-start gap-2.5">
              <Info className="w-4 h-4 text-muted-foreground shrink-0 mt-0.5" />
              <div className="min-w-0 flex-1">
                <p className="text-xs font-medium">对外接入（全部可选）</p>
                <p className="text-[11px] text-muted-foreground mt-0.5 leading-relaxed">
                  接入 <span className="font-medium">丰声 NEXT</span> 发布为群聊机器人；发布到 <span className="font-medium">Agent Hub</span> 获得可视化运行监控。不需要可全部跳过，智能体仍可正常使用。
                </p>
              </div>
            </div>

            {/* 丰声 NEXT 群聊机器人 */}
            <div className="border border-border rounded-lg bg-card">
              <div className="px-5 py-3 border-b border-border flex items-center justify-between gap-3">
                <div className="min-w-0">
                  <div className="text-xs font-semibold flex items-center gap-1.5">
                    <MessageSquare className="w-3.5 h-3.5 text-primary" />
                    丰声 NEXT 群聊机器人
                    <Badge variant="outline" className="text-[10px] h-4 px-1.5 text-muted-foreground">可选</Badge>
                  </div>
                  <p className="text-[11px] text-muted-foreground mt-0.5">把智能体接入丰声 NEXT 群聊（基于 Function Calling），成员 @ 机器人即可触发</p>
                </div>
                <Badge
                  variant="outline"
                  className={`text-[10px] gap-1 ${fsConnected ? "text-emerald-600 border-emerald-600/40 bg-emerald-500/10" : "text-muted-foreground"}`}
                >
                  <span className={`w-1.5 h-1.5 rounded-full ${fsConnected ? "bg-emerald-500" : "bg-muted-foreground/50"}`} />
                  {fsConnected ? "已连接" : "未连接"}
                </Badge>
              </div>
              <div className="p-5 space-y-3">
                <div>
                  <Label className="text-xs">Client ID（AppKey）</Label>
                  <Input className="mt-1.5 h-8 text-xs font-mono" placeholder="企业应用 AppKey" value={fsAppKey} onChange={(e) => setFsAppKey(e.target.value)} />
                </div>
                <div>
                  <Label className="text-xs">Client Secret（AppSecret）</Label>
                  <div className="relative mt-1.5">
                    <Input className="h-8 text-xs font-mono pr-9" type={fsSecretVisible ? "text" : "password"} placeholder="企业应用 AppSecret" value={fsAppSecret} onChange={(e) => setFsAppSecret(e.target.value)} />
                    <button type="button" onClick={() => setFsSecretVisible(!fsSecretVisible)} className="absolute right-2 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground">
                      {fsSecretVisible ? <EyeOff className="w-3.5 h-3.5" /> : <Eye className="w-3.5 h-3.5" />}
                    </button>
                  </div>
                </div>
                <div>
                  <Label className="text-xs">Robot Code</Label>
                  <Input className="mt-1.5 h-8 text-xs font-mono" placeholder="机器人编码" value={fsRobotCode} onChange={(e) => setFsRobotCode(e.target.value)} />
                </div>
                <div className="flex justify-end pt-1">
                  <Button
                    size="sm"
                    variant={fsConnected ? "outline" : "default"}
                    className="h-8 text-xs gap-1.5"
                    onClick={() => {
                      if (!fsAppKey || !fsAppSecret || !fsRobotCode) {
                        toast({ title: "请先填写完整的应用凭证", variant: "destructive" });
                        return;
                      }
                      setFsConnected(true);
                      toast({ title: "丰声 NEXT 机器人已连接", description: `Robot ${fsRobotCode}` });
                    }}
                  >
                    {fsConnected ? <CheckCircle2 className="w-3.5 h-3.5" /> : <Link2 className="w-3.5 h-3.5" />}
                    {fsConnected ? "已连接" : "连接"}
                  </Button>
                </div>
              </div>
            </div>

            {/* Agent Hub 发布 */}
            <div className="border border-border rounded-lg bg-card">
              <div className="px-5 py-3 flex items-center justify-between gap-3">
                <div className="min-w-0">
                  <div className="text-xs font-semibold flex items-center gap-1.5">
                    <FolderKanban className="w-3.5 h-3.5 text-primary" />
                    Agent Hub
                    <Badge variant="outline" className="text-[10px] h-4 px-1.5 text-muted-foreground">可选</Badge>
                  </div>
                  <p className="text-[11px] text-muted-foreground mt-0.5">开启后，智能体保存时将同步发布到 Agent Hub，提供运行状态、调用次数、错误率等可视化监控</p>
                </div>
                <div className="flex items-center gap-2">
                  <Switch
                    checked={hubEnabled}
                    onCheckedChange={(v) => {
                      setHubEnabled(v);
                      toast({ title: v ? "已开启 Agent Hub 同步" : "已关闭 Agent Hub 同步" });
                    }}
                  />
                  <Badge
                    variant="outline"
                    className={`text-[10px] gap-1 ${hubEnabled ? "text-emerald-600 border-emerald-600/40 bg-emerald-500/10" : "text-muted-foreground"}`}
                  >
                    <span className={`w-1.5 h-1.5 rounded-full ${hubEnabled ? "bg-emerald-500" : "bg-muted-foreground/50"}`} />
                    {hubEnabled ? "已开启" : "未开启"}
                  </Badge>
                </div>
              </div>
            </div>

            <div className="flex justify-between mt-3">
              <Button size="sm" variant="ghost" className="h-8 text-xs gap-1" onClick={() => setCurrentTab("prompt")}>
                <ArrowLeft className="w-3 h-3" /> 上一步
              </Button>
              <Button
                size="sm"
                className="h-8 text-xs gap-1.5"
                disabled={!channelsValid}
                onClick={() => setCurrentTab("debug")}
                title={channelsValid ? "下一步：调试" : "已启用的接入项尚未完成连接"}
              >
                下一步：调试 <ArrowRight className="w-3 h-3" />
              </Button>
            </div>
          </TabsContent>

          {/* Debug */}
          <TabsContent value="debug" className="mt-4 space-y-4">
            <div className="border border-border rounded-lg px-4 py-3 bg-gradient-to-r from-primary/10 to-primary/5 flex items-center justify-between gap-3">
              <div className="flex items-center gap-2.5">
                <Bug className="w-4 h-4 text-primary shrink-0" />
                <p className="text-xs">
                  <span className="font-medium">调试智能体</span>
                  <span className="text-muted-foreground"> · 左侧与调试 AI 沟通配置；右侧直接与智能体对话验证</span>
                </p>
              </div>
              {debugChanges.length > 0 && (
                <Badge variant="secondary" className="text-[10px] gap-1">
                  <CheckCircle2 className="w-3 h-3" />
                  调试期已优化 {debugChanges.length} 项
                </Badge>
              )}
            </div>

            <div className="grid grid-cols-2 gap-4">
              {/* Left: Debug Assistant */}
              <div className="border border-border rounded-lg bg-card flex flex-col h-[clamp(380px,calc(100vh-260px),560px)]">
                <div className="px-3 h-10 shrink-0 border-b border-border flex items-center gap-1.5">
                  <Bot className="w-3.5 h-3.5 text-primary" />
                  <span className="text-xs font-semibold">调试助手</span>
                  <Badge variant="outline" className="text-[10px] h-4">AI</Badge>
                </div>
                <div className="flex-1 overflow-auto p-4 space-y-3">
                  {assistantMessages.length === 0 && (
                    <div className="h-full flex flex-col items-center justify-center text-center text-muted-foreground gap-2 px-4">
                      <Bot className="w-7 h-7 opacity-30" />
                      <p className="text-xs">在右侧发起一轮调试后，我会主动告诉你做了哪些优化</p>
                      <p className="text-[10px] leading-relaxed">你也可以直接和我说："帮我修改提示词"、"补充某个能力的用途"</p>
                    </div>
                  )}
                  {assistantMessages.map((msg, i) => (
                    <div key={i} className={`flex ${msg.role === "user" ? "justify-end" : "justify-start"}`}>
                      <div className={`max-w-[85%] rounded-lg px-3 py-2 text-xs whitespace-pre-wrap leading-relaxed ${
                        msg.role === "user" ? "bg-primary text-primary-foreground" : "bg-muted"
                      }`}>
                        {msg.content}
                        {msg.suggestion && (
                          <div className="mt-2 pt-2 border-t border-border/60 flex items-center gap-2">
                            {msg.suggestion.status === "pending" && (
                              <>
                                <Button size="sm" className="h-6 text-[11px] px-2 gap-1" onClick={() => adoptSuggestion(msg.suggestion!)}>
                                  <CheckCircle2 className="w-3 h-3" /> 采纳
                                </Button>
                                <Button size="sm" variant="ghost" className="h-6 text-[11px] px-2" onClick={() => rejectSuggestion(msg.suggestion!)}>
                                  忽略
                                </Button>
                              </>
                            )}
                            {msg.suggestion.status === "adopted" && (
                              <span className="inline-flex items-center gap-1 text-[11px] text-emerald-600">
                                <CheckCircle2 className="w-3 h-3" /> 已采纳
                              </span>
                            )}
                            {msg.suggestion.status === "rejected" && (
                              <span className="text-[11px] text-muted-foreground">已忽略</span>
                            )}
                          </div>
                        )}
                      </div>
                    </div>
                  ))}
                  {assistantThinking && (
                    <div className="flex justify-start">
                      <AIStatusPill stages={["分析你的反馈", "调整提示词", "生成回复"]} />
                    </div>
                  )}
                </div>
                <div className="border-t border-border p-3 flex items-center gap-2">
                  <Input
                    className="h-8 text-xs"
                    placeholder='告诉我要怎么调整，例如"帮我精简提示词"'
                    value={assistantInput}
                    onChange={(e) => setAssistantInput(e.target.value)}
                    onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); sendAssistantMessage(); } }}
                  />
                  <Button size="sm" className="h-8 text-xs gap-1.5" onClick={sendAssistantMessage} disabled={assistantThinking || !assistantInput.trim()}>
                    <Send className="w-3 h-3" /> 发送
                  </Button>
                </div>
              </div>

              {/* Right: Agent Run with transcript / debug toggle */}
              <div className="border border-border rounded-lg bg-card flex flex-col h-[clamp(380px,calc(100vh-260px),560px)]">
                <div className="px-3 h-10 shrink-0 border-b border-border flex items-center gap-1.5">
                  <Bot className="w-3.5 h-3.5 text-primary shrink-0" />
                  <span className="text-xs font-semibold shrink-0">智能体运行</span>
                  {debugRunning && <RunningIndicator />}
                </div>
                <div className="flex-1 min-h-0">
                  <RunDualView
                    showTranscriptSearch={false}
                    transcriptEvents={(() => {
                      const evs: TranscriptEvent[] = [];
                      runMessages.forEach((m, i) => {
                        if (m.role === "user") evs.push({ id: `u${i}`, type: "user", content: m.content });
                        else if (m.status === "error") evs.push({ id: `e${i}`, type: "error", message: m.content });
                        else {
                          if (m.tool) evs.push({
                            id: `t${i}`, type: "tools",
                            calls: [{ id: `c${i}`, kind: "mcp", name: m.tool, summary: "调用成功", status: "success" }],
                          });
                          evs.push({ id: `a${i}`, type: "agent", content: m.content });
                        }
                      });
                      if (runMessages.length === 0) {
                        evs.push({ id: "empty", type: "system", message: "输入示例任务即可开始调试" });
                      }
                      return evs;
                    })()}
                    debugEvents={debugLogs.map((l) => ({
                      id: String(l.id),
                      ts: l.ts,
                      type: `log.${l.level}`,
                      data: { message: l.message, ...(l.meta ? { meta: l.meta } : {}) },
                    }))}
                    debugMeta={[
                      { label: "模型", value: model },
                      { label: "事件数", value: String(debugLogs.length) },
                    ]}
                  />
                </div>
                <div className="border-t border-border p-3 flex items-center gap-2 shrink-0">
                  <Button
                    type="button"
                    size="icon"
                    variant={voiceRecording ? "default" : "outline"}
                    className={`h-8 w-8 shrink-0 ${voiceRecording ? "animate-pulse" : ""}`}
                    onClick={toggleVoice}
                    title={voiceRecording ? "结束语音输入" : "语音输入"}
                  >
                    {voiceRecording ? <MicOff className="w-3.5 h-3.5" /> : <Mic className="w-3.5 h-3.5" />}
                  </Button>
                  <Input
                    className="h-8 text-xs"
                    placeholder={voiceRecording ? "正在录音…再次点击麦克风结束" : "输入测试任务，回车发送"}
                    value={debugInput}
                    onChange={(e) => setDebugInput(e.target.value)}
                    onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); runDebug(); } }}
                  />
                  <Button size="sm" className="h-8 text-xs gap-1.5" onClick={() => runDebug()} disabled={debugRunning || !debugInput.trim()}>
                    <Send className="w-3 h-3" /> 发送
                  </Button>
                </div>
              </div>
            </div>
          </TabsContent>
        </Tabs>
      </div>

      <Dialog open={publishOpen} onOpenChange={setPublishOpen}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle className="text-sm flex items-center gap-1.5">
              <FolderKanban className="w-4 h-4 text-primary" />
              保存到项目管理
            </DialogTitle>
            <DialogDescription className="text-[11px]">
              确认基础信息后保存为新版本。如需发布，请在项目管理卡片或详情页右上角的「发布」按钮中操作。
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-3 py-1">
            <div>
              <Label className="text-xs">头像</Label>
              <div className="mt-1.5 flex items-center gap-3">
                <div className="w-14 h-14 rounded-lg border border-border bg-muted/40 overflow-hidden flex items-center justify-center shrink-0">
                  {generatingAvatar ? (
                    <Loader2 className="w-4 h-4 animate-spin text-muted-foreground" />
                  ) : (
                    <img src={avatarUrl} alt="智能体头像" className="w-full h-full object-cover" />
                  )}
                </div>
                <div className="flex-1 min-w-0">
                  <Button type="button" variant="outline" size="sm" className="h-7 text-xs gap-1.5" onClick={regenerateAvatar} disabled={generatingAvatar}>
                    <RefreshCw className={`w-3 h-3 ${generatingAvatar ? "animate-spin" : ""}`} />
                    {generatingAvatar ? "生成中…" : "AI 重新生成"}
                  </Button>
                </div>
              </div>
            </div>
            <div>
              <Label className="text-xs">名称 <span className="text-destructive">*</span></Label>
              <Input className="mt-1.5 h-8 text-xs" value={name} onChange={(e) => setName(e.target.value)} placeholder="例如：财务月报助手" />
            </div>
            <div>
              <Label className="text-xs">描述</Label>
              <Textarea className="mt-1.5 text-xs" rows={3} value={description} onChange={(e) => setDescription(e.target.value)} placeholder="一句话描述智能体能力" />
            </div>
            <div>
              <Label className="text-xs">分类</Label>
              <Select value={category} onValueChange={setCategory}>
                <SelectTrigger className="mt-1.5 h-8 text-xs"><SelectValue /></SelectTrigger>
                <SelectContent>
                  {categories.map((c) => <SelectItem key={c} value={c} className="text-xs">{c}</SelectItem>)}
                </SelectContent>
              </Select>
            </div>
            {debugChanges.length > 0 && (
              <div className="border border-primary/30 bg-primary/5 rounded-lg p-3 space-y-1.5">
                <div className="flex items-center gap-1.5 text-xs font-medium text-primary">
                  <CheckCircle2 className="w-3.5 h-3.5" />
                  本次保存将包含 {debugChanges.length} 项调试期改动
                </div>
                <ul className="text-[11px] text-muted-foreground space-y-1 pl-5 list-disc leading-relaxed">
                  {debugChanges.map((c, i) => (
                    <li key={i}>{c.summary}</li>
                  ))}
                </ul>
              </div>
            )}
          </div>
          <DialogFooter>
            <Button variant="outline" size="sm" className="h-8 text-xs" onClick={() => setPublishOpen(false)}>取消</Button>
            <Button size="sm" className="h-8 text-xs gap-1.5" onClick={handleSave}>
              <Save className="w-3 h-3" /> 保存
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* 配置文档查看 */}
      <Dialog open={specOpen} onOpenChange={setSpecOpen}>
        <DialogContent className="max-w-3xl">
          <DialogHeader>
            <DialogTitle className="text-sm">智能体配置文档</DialogTitle>
            <DialogDescription className="text-xs">
              当前组装结果的结构化描述，可用于版本管理或外部导入
            </DialogDescription>
          </DialogHeader>
          <div className="flex items-center justify-between border-b border-border pb-2">
            <div className="flex gap-1">
              {(["yaml", "json"] as const).map((f) => (
                <button
                  key={f}
                  onClick={() => setSpecFormat(f)}
                  className={`px-2.5 py-1 rounded text-xs transition-colors ${
                    specFormat === f ? "bg-secondary text-foreground font-medium" : "text-muted-foreground hover:text-foreground"
                  }`}
                >
                  {f.toUpperCase()}
                </button>
              ))}
            </div>
            <div className="flex items-center gap-1">
              <Button variant="ghost" size="sm" className="h-7 text-xs gap-1" onClick={copySpec}>
                <Copy className="w-3 h-3" />复制
              </Button>
              <Button variant="ghost" size="sm" className="h-7 text-xs gap-1" onClick={downloadSpec}>
                <ArrowRight className="w-3 h-3 rotate-90" />下载
              </Button>
            </div>
          </div>
          <div className="max-h-[60vh] overflow-auto bg-muted/30 rounded border border-border">
            <div className="flex min-h-full">
              <div className="select-none text-right pr-3 pl-3 py-3 text-[10px] font-mono text-muted-foreground/50 leading-relaxed shrink-0">
                {specContent.split("\n").map((_, i) => <div key={i}>{i + 1}</div>)}
              </div>
              <pre className="flex-1 py-3 pr-4 text-[11px] font-mono leading-relaxed text-foreground whitespace-pre-wrap break-all">
                {specContent}
              </pre>
            </div>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
};

export default CreateAgentManualPage;
